-- Migration: Create watchers table and add notification infrastructure
-- This migration implements the watchers functionality allowing users to "watch"
-- organizations and meetings to receive notifications about relevant events.

-- ============================================================================
-- 1. Create watchers table
-- ============================================================================

CREATE TABLE "public"."watchers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_id" uuid NOT NULL,
    "dashboard_id" bigint NOT NULL,
    "organization_id" bigint NULL,
    "meeting_id" bigint NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT "watchers_user_id_fkey"
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT "watchers_dashboard_id_fkey"
        FOREIGN KEY (dashboard_id)
        REFERENCES dashboards(id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT "watchers_organization_id_fkey"
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT "watchers_meeting_id_fkey"
        FOREIGN KEY (meeting_id)
        REFERENCES meetings(id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    -- Either watching an organization OR a meeting, not both
    CONSTRAINT "watchers_org_or_meeting_check"
        CHECK (
            (organization_id IS NOT NULL AND meeting_id IS NULL) OR
            (organization_id IS NULL AND meeting_id IS NOT NULL)
        )
);

-- ============================================================================
-- 2. Create unique indexes for watchers
-- ============================================================================

-- Unique constraint: user can only watch an org/meeting once
CREATE UNIQUE INDEX watchers_user_org_unique
    ON public.watchers (user_id, organization_id)
    WHERE meeting_id IS NULL;

CREATE UNIQUE INDEX watchers_user_meeting_unique
    ON public.watchers (user_id, meeting_id)
    WHERE organization_id IS NULL;

-- ============================================================================
-- 3. Create indexes for faster lookups
-- ============================================================================

CREATE INDEX watchers_organization_id_idx ON public.watchers (organization_id);
CREATE INDEX watchers_meeting_id_idx ON public.watchers (meeting_id);
CREATE INDEX watchers_user_id_idx ON public.watchers (user_id);
CREATE INDEX watchers_dashboard_id_idx ON public.watchers (dashboard_id);

-- ============================================================================
-- 4. Enable RLS on watchers table
-- ============================================================================

ALTER TABLE "public"."watchers" ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. Create RLS policies for watchers
-- ============================================================================

-- Users can view their own watchers
CREATE POLICY "Users can view their own watchers"
    ON "public"."watchers"
    FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

-- Users can create their own watchers
CREATE POLICY "Users can create their own watchers"
    ON "public"."watchers"
    FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Users can delete their own watchers
CREATE POLICY "Users can delete their own watchers"
    ON "public"."watchers"
    FOR DELETE
    TO authenticated
    USING (user_id = auth.uid());

-- ============================================================================
-- 6. Grant permissions on watchers table
-- ============================================================================

GRANT SELECT, INSERT, DELETE ON TABLE "public"."watchers" TO "authenticated";
GRANT SELECT, INSERT, DELETE ON TABLE "public"."watchers" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."watchers_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."watchers_id_seq" TO "service_role";

-- ============================================================================
-- 7. Add RLS policies for notification_settings (missing from original setup)
-- ============================================================================

-- Users can view their own notification settings
CREATE POLICY "Users can view their own notification settings"
    ON "public"."notification_settings"
    FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

-- Users can create their own notification settings
CREATE POLICY "Users can create their own notification settings"
    ON "public"."notification_settings"
    FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Users can update their own notification settings
CREATE POLICY "Users can update their own notification settings"
    ON "public"."notification_settings"
    FOR UPDATE
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- Users can delete their own notification settings
CREATE POLICY "Users can delete their own notification settings"
    ON "public"."notification_settings"
    FOR DELETE
    TO authenticated
    USING (user_id = auth.uid());

-- ============================================================================
-- 8. Enable realtime with full row data for notifications table
-- ============================================================================

-- This allows real-time subscriptions to get full row data for inserts/updates/deletes
ALTER TABLE "public"."notifications" REPLICA IDENTITY FULL;

-- ============================================================================
-- 9. Enable realtime with full row data for watchers table
-- ============================================================================

ALTER TABLE "public"."watchers" REPLICA IDENTITY FULL;

-- ============================================================================
-- 10. Enable realtime with full row data for notification_settings table
-- ============================================================================

ALTER TABLE "public"."notification_settings" REPLICA IDENTITY FULL;

-- ============================================================================
-- 10. Create webhook triggers for meeting creation
-- ============================================================================

CREATE TRIGGER "meetings/insert"
    AFTER INSERT ON public.meetings
    FOR EACH ROW
    EXECUTE FUNCTION supabase_functions.http_request(
        'http://host.docker.internal:3000/webhooks/meetings/insert',
        'POST',
        '{"Content-type":"application/json"}',
        '{}',
        '5000'
    );

-- ============================================================================
-- 11. Create webhook triggers for log creation (comments)
-- ============================================================================

CREATE TRIGGER "logs/insert"
    AFTER INSERT ON public.logs
    FOR EACH ROW
    EXECUTE FUNCTION supabase_functions.http_request(
        'http://host.docker.internal:3000/webhooks/logs/insert',
        'POST',
        '{"Content-type":"application/json"}',
        '{}',
        '5000'
    );

alter publication supabase_realtime add table logs;
alter publication supabase_realtime add table notification_settings;
alter publication supabase_realtime add table notifications;
alter publication supabase_realtime add table watchers;
