create type "public"."meeting_log_types" as enum ('lifecycle', 'comment');

create table "public"."dashboard_users" (
    "user_id" uuid not null,
    "dashboard_id" bigint not null,
    "can_manage_users" boolean not null default false,
    "is_admin" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."dashboard_users" enable row level security;

create table "public"."dashboards" (
    "id" bigint generated by default as identity not null,
    "label" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."dashboards" enable row level security;

create table "public"."meeting_documents" (
    "id" bigint generated by default as identity not null,
    "meeting_id" bigint not null,
    "filename" text not null,
    "file_hash" text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid
);


alter table "public"."meeting_documents" enable row level security;

create table "public"."meeting_logs" (
    "id" bigint generated by default as identity not null,
    "meeting_id" bigint not null,
    "text" text not null,
    "is_bot_action" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "type" meeting_log_types not null
);


alter table "public"."meeting_logs" enable row level security;

create table "public"."meetings" (
    "id" bigint generated by default as identity not null,
    "organization_id" bigint not null,
    "name" text not null,
    "meeting_date" date not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid
);


alter table "public"."meetings" enable row level security;

create table "public"."organizations" (
    "id" bigint generated by default as identity not null,
    "dashboard_id" bigint not null,
    "name" text not null,
    "url" text not null,
    "sync_error" text,
    "last_synced" date,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."organizations" enable row level security;

CREATE UNIQUE INDEX dashboard_users_pkey ON public.dashboard_users USING btree (user_id, dashboard_id);

CREATE UNIQUE INDEX dashboards_pkey ON public.dashboards USING btree (id);

CREATE UNIQUE INDEX meeting_document_pkey ON public.meeting_documents USING btree (id);

CREATE UNIQUE INDEX meeting_logs_pkey ON public.meeting_logs USING btree (id);

CREATE UNIQUE INDEX meetings_pkey ON public.meetings USING btree (id);

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);

alter table "public"."dashboard_users" add constraint "dashboard_users_pkey" PRIMARY KEY using index "dashboard_users_pkey";

alter table "public"."dashboards" add constraint "dashboards_pkey" PRIMARY KEY using index "dashboards_pkey";

alter table "public"."meeting_documents" add constraint "meeting_document_pkey" PRIMARY KEY using index "meeting_document_pkey";

alter table "public"."meeting_logs" add constraint "meeting_logs_pkey" PRIMARY KEY using index "meeting_logs_pkey";

alter table "public"."meetings" add constraint "meetings_pkey" PRIMARY KEY using index "meetings_pkey";

alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

alter table "public"."dashboard_users" add constraint "dashboard_users_dashboard_id_fkey" FOREIGN KEY (dashboard_id) REFERENCES dashboards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dashboard_users" validate constraint "dashboard_users_dashboard_id_fkey";

alter table "public"."dashboard_users" add constraint "dashboard_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dashboard_users" validate constraint "dashboard_users_user_id_fkey";

alter table "public"."meeting_documents" add constraint "meeting_document_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."meeting_documents" validate constraint "meeting_document_created_by_fkey";

alter table "public"."meeting_documents" add constraint "meeting_document_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meeting_documents" validate constraint "meeting_document_meeting_id_fkey";

alter table "public"."meeting_logs" add constraint "meeting_logs_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."meeting_logs" validate constraint "meeting_logs_created_by_fkey";

alter table "public"."meeting_logs" add constraint "meeting_logs_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meeting_logs" validate constraint "meeting_logs_meeting_id_fkey";

alter table "public"."meetings" add constraint "meetings_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."meetings" validate constraint "meetings_created_by_fkey";

alter table "public"."meetings" add constraint "meetings_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meetings" validate constraint "meetings_organization_id_fkey";

alter table "public"."organizations" add constraint "organizations_dashboard_id_fkey" FOREIGN KEY (dashboard_id) REFERENCES dashboards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."organizations" validate constraint "organizations_dashboard_id_fkey";

grant delete on table "public"."dashboard_users" to "anon";

grant insert on table "public"."dashboard_users" to "anon";

grant references on table "public"."dashboard_users" to "anon";

grant select on table "public"."dashboard_users" to "anon";

grant trigger on table "public"."dashboard_users" to "anon";

grant truncate on table "public"."dashboard_users" to "anon";

grant update on table "public"."dashboard_users" to "anon";

grant delete on table "public"."dashboard_users" to "authenticated";

grant insert on table "public"."dashboard_users" to "authenticated";

grant references on table "public"."dashboard_users" to "authenticated";

grant select on table "public"."dashboard_users" to "authenticated";

grant trigger on table "public"."dashboard_users" to "authenticated";

grant truncate on table "public"."dashboard_users" to "authenticated";

grant update on table "public"."dashboard_users" to "authenticated";

grant delete on table "public"."dashboard_users" to "service_role";

grant insert on table "public"."dashboard_users" to "service_role";

grant references on table "public"."dashboard_users" to "service_role";

grant select on table "public"."dashboard_users" to "service_role";

grant trigger on table "public"."dashboard_users" to "service_role";

grant truncate on table "public"."dashboard_users" to "service_role";

grant update on table "public"."dashboard_users" to "service_role";

grant delete on table "public"."dashboards" to "anon";

grant insert on table "public"."dashboards" to "anon";

grant references on table "public"."dashboards" to "anon";

grant select on table "public"."dashboards" to "anon";

grant trigger on table "public"."dashboards" to "anon";

grant truncate on table "public"."dashboards" to "anon";

grant update on table "public"."dashboards" to "anon";

grant delete on table "public"."dashboards" to "authenticated";

grant insert on table "public"."dashboards" to "authenticated";

grant references on table "public"."dashboards" to "authenticated";

grant select on table "public"."dashboards" to "authenticated";

grant trigger on table "public"."dashboards" to "authenticated";

grant truncate on table "public"."dashboards" to "authenticated";

grant update on table "public"."dashboards" to "authenticated";

grant delete on table "public"."dashboards" to "service_role";

grant insert on table "public"."dashboards" to "service_role";

grant references on table "public"."dashboards" to "service_role";

grant select on table "public"."dashboards" to "service_role";

grant trigger on table "public"."dashboards" to "service_role";

grant truncate on table "public"."dashboards" to "service_role";

grant update on table "public"."dashboards" to "service_role";

grant delete on table "public"."meeting_documents" to "anon";

grant insert on table "public"."meeting_documents" to "anon";

grant references on table "public"."meeting_documents" to "anon";

grant select on table "public"."meeting_documents" to "anon";

grant trigger on table "public"."meeting_documents" to "anon";

grant truncate on table "public"."meeting_documents" to "anon";

grant update on table "public"."meeting_documents" to "anon";

grant delete on table "public"."meeting_documents" to "authenticated";

grant insert on table "public"."meeting_documents" to "authenticated";

grant references on table "public"."meeting_documents" to "authenticated";

grant select on table "public"."meeting_documents" to "authenticated";

grant trigger on table "public"."meeting_documents" to "authenticated";

grant truncate on table "public"."meeting_documents" to "authenticated";

grant update on table "public"."meeting_documents" to "authenticated";

grant delete on table "public"."meeting_documents" to "service_role";

grant insert on table "public"."meeting_documents" to "service_role";

grant references on table "public"."meeting_documents" to "service_role";

grant select on table "public"."meeting_documents" to "service_role";

grant trigger on table "public"."meeting_documents" to "service_role";

grant truncate on table "public"."meeting_documents" to "service_role";

grant update on table "public"."meeting_documents" to "service_role";

grant delete on table "public"."meeting_logs" to "anon";

grant insert on table "public"."meeting_logs" to "anon";

grant references on table "public"."meeting_logs" to "anon";

grant select on table "public"."meeting_logs" to "anon";

grant trigger on table "public"."meeting_logs" to "anon";

grant truncate on table "public"."meeting_logs" to "anon";

grant update on table "public"."meeting_logs" to "anon";

grant delete on table "public"."meeting_logs" to "authenticated";

grant insert on table "public"."meeting_logs" to "authenticated";

grant references on table "public"."meeting_logs" to "authenticated";

grant select on table "public"."meeting_logs" to "authenticated";

grant trigger on table "public"."meeting_logs" to "authenticated";

grant truncate on table "public"."meeting_logs" to "authenticated";

grant update on table "public"."meeting_logs" to "authenticated";

grant delete on table "public"."meeting_logs" to "service_role";

grant insert on table "public"."meeting_logs" to "service_role";

grant references on table "public"."meeting_logs" to "service_role";

grant select on table "public"."meeting_logs" to "service_role";

grant trigger on table "public"."meeting_logs" to "service_role";

grant truncate on table "public"."meeting_logs" to "service_role";

grant update on table "public"."meeting_logs" to "service_role";

grant delete on table "public"."meetings" to "anon";

grant insert on table "public"."meetings" to "anon";

grant references on table "public"."meetings" to "anon";

grant select on table "public"."meetings" to "anon";

grant trigger on table "public"."meetings" to "anon";

grant truncate on table "public"."meetings" to "anon";

grant update on table "public"."meetings" to "anon";

grant delete on table "public"."meetings" to "authenticated";

grant insert on table "public"."meetings" to "authenticated";

grant references on table "public"."meetings" to "authenticated";

grant select on table "public"."meetings" to "authenticated";

grant trigger on table "public"."meetings" to "authenticated";

grant truncate on table "public"."meetings" to "authenticated";

grant update on table "public"."meetings" to "authenticated";

grant delete on table "public"."meetings" to "service_role";

grant insert on table "public"."meetings" to "service_role";

grant references on table "public"."meetings" to "service_role";

grant select on table "public"."meetings" to "service_role";

grant trigger on table "public"."meetings" to "service_role";

grant truncate on table "public"."meetings" to "service_role";

grant update on table "public"."meetings" to "service_role";

grant delete on table "public"."organizations" to "anon";

grant insert on table "public"."organizations" to "anon";

grant references on table "public"."organizations" to "anon";

grant select on table "public"."organizations" to "anon";

grant trigger on table "public"."organizations" to "anon";

grant truncate on table "public"."organizations" to "anon";

grant update on table "public"."organizations" to "anon";

grant delete on table "public"."organizations" to "authenticated";

grant insert on table "public"."organizations" to "authenticated";

grant references on table "public"."organizations" to "authenticated";

grant select on table "public"."organizations" to "authenticated";

grant trigger on table "public"."organizations" to "authenticated";

grant truncate on table "public"."organizations" to "authenticated";

grant update on table "public"."organizations" to "authenticated";

grant delete on table "public"."organizations" to "service_role";

grant insert on table "public"."organizations" to "service_role";

grant references on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "service_role";

grant trigger on table "public"."organizations" to "service_role";

grant truncate on table "public"."organizations" to "service_role";

grant update on table "public"."organizations" to "service_role";

ALTER TABLE dashboard_users REPLICA IDENTITY FULL;
ALTER TABLE dashboards REPLICA IDENTITY FULL;
ALTER TABLE organizations REPLICA IDENTITY FULL;
ALTER TABLE meetings REPLICA IDENTITY FULL;
ALTER TABLE meeting_documents REPLICA IDENTITY FULL;
ALTER TABLE meeting_logs REPLICA IDENTITY FULL;
ALTER TABLE users REPLICA IDENTITY FULL;